[package]
name = "sample"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
tempfile = "3.13"
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
ron = "0.8"
serde = { version = "1.0", features = ["derive"] }
